rules:
  - id: cross-function-taint-propagation
    languages:
      - python
      - javascript
      - typescript
      - java
    message: |
      Cross-function taint propagation: Tainted data flows through function call chains to sensitive sinks.
      Ensure proper validation at each function boundary.
    severity: WARNING
    pattern: $SINK($TAINTED_DATA)

  - id: null-pointer-dereference
    languages:
      - python
      - javascript
      - typescript
      - java
      - c
      - cpp
    message: |
      Null pointer dereference: Potential dereference of null value causing program crash.
      Add null checks before dereferencing.
    severity: ERROR
    pattern: $OBJECT.$METHOD()

  - id: resource-leak-detection
    languages:
      - python
      - java
      - javascript
      - c
      - cpp
    message: |
      Resource leak: File, database connection, or network connection not properly closed.
      Ensure resources are properly closed after use.
    severity: WARNING
    pattern: open($FILE_PATH)

  - id: buffer-overflow-detection
    languages:
      - c
      - cpp
      - python
      - java
    message: |
      Buffer overflow: Array or buffer access may exceed boundaries.
      Add bounds checking before array access.
    severity: ERROR
    pattern: $ARRAY[$INDEX]

  - id: use-after-free
    languages:
      - c
      - cpp
      - python
      - java
    message: |
      Use after free: Object or memory accessed after being freed.
      Ensure memory safety by preventing use-after-free vulnerabilities.
    severity: ERROR
    pattern: $OBJECT.$METHOD()

  - id: race-condition-detection
    languages:
      - python
      - java
      - javascript
      - typescript
    message: |
      Race condition: Shared resource accessed without proper synchronization in multi-threaded environment.
      Use synchronization mechanisms to prevent race conditions.
    severity: WARNING
    pattern: $SHARED_VARIABLE = $VALUE

  - id: information-leak-detection
    languages:
      - python
      - java
      - javascript
      - typescript
    message: |
      Information leak: Sensitive information may be exposed through exceptions or logs.
      Avoid logging sensitive information and sanitize error messages.
    severity: WARNING
    pattern: print($SENSITIVE_DATA)