services:
  # ==================== Monitoring Services ====================
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../monitoring/alerts:/etc/prometheus/alerts
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ../monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/data'
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

  # ==================== Meta Services ====================
  metad0:
    hostname: metad0
    image: vesoft/nebula-metad:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=metad0
      - --ws_ip=metad0
      - --port=9559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./data/meta0:/data
      - ./logs/metad0:/logs
    ports:
      - 9559:9559
      - 19559:19559
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "metad0", "-port", "9559", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  metad1:
    hostname: metad1
    image: vesoft/nebula-metad:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=metad1
      - --ws_ip=metad1
      - --port=9559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./data/meta1:/data
      - ./logs/metad1:/logs
    ports:
      - 9560:9559
      - 19560:19559
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "metad1", "-port", "9559", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  metad2:
    hostname: metad2
    image: vesoft/nebula-metad:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=metad2
      - --ws_ip=metad2
      - --port=9559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./data/meta2:/data
      - ./logs/metad2:/logs
    ports:
      - 9561:9559
      - 19561:19559
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "metad2", "-port", "9559", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # ==================== Storage Services ====================
  storaged0:
    hostname: storaged0
    image: vesoft/nebula-storaged:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=9779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./data/storage0:/data
      - ./logs/storaged0:/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    ports:
      - 9779:9779
      - 19779:19779
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "storaged0", "-port", "9779", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS storage;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  storaged1:
    hostname: storaged1
    image: vesoft/nebula-storaged:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=storaged1
      - --ws_ip=storaged1
      - --port=9779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./data/storage1:/data
      - ./logs/storaged1:/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    ports:
      - 9780:9779
      - 19780:19779
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "storaged1", "-port", "9779", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS storage;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  storaged2:
    hostname: storaged2
    image: vesoft/nebula-storaged:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=storaged2
      - --ws_ip=storaged2
      - --port=9779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./data/storage2:/data
      - ./logs/storaged2:/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    ports:
      - 9781:9779
      - 19781:19779
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "storaged2", "-port", "9779", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS storage;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

# ==================== Graph Service ====================
  graphd:
    hostname: graphd
    image: vesoft/nebula-graphd:v3.8.0
    environment:
      TZ: "Asia/Shanghai"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd
      - --ws_ip=graphd
      - --enable_authorize=true
      - --log_dir=/logs
      - --minloglevel=0
    volumes:
      - ./logs/graphd:/logs
    depends_on:
      - metad0
      - metad1
      - metad2
      - storaged0
      - storaged1
      - storaged2
    ports:
      - 9669:9669
      - 19669:19669
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker", "exec", "console", "nebula-console", "-addr", "graphd", "-port", "9669", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS;"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
  meta0:
  meta1:
  meta2:
  storage0:
  storage1:
  storage2:
  logs:

networks:
  monitoring:
    driver: bridge