rules:
  - id: direct-object-reference
    languages:
      - python
      - javascript
      - typescript
      - java
    message: |
      Authorization flaw: Direct object reference without permission check.
      Always verify user permissions before accessing resources.
    severity: ERROR
    pattern: |
      user_id = request.GET['id']
      ...
      delete_file(user_id)

  - id: file-operation-permission
    languages:
      - python
      - javascript
      - typescript
      - java
    message: |
      Authorization flaw: File operation without permission check.
      Verify user permissions before file operations.
    severity: ERROR
    pattern: |
      file_path = request.GET['path']
      ...
      os.remove(file_path)

  - id: role-check-missing-auth
    languages:
      - python
      - javascript
      - typescript
      - java
    message: |
      Authorization flaw: Role check without authentication verification.
      Ensure user is authenticated before role checks.
    severity: ERROR
    pattern: |
      if user.role == 'admin':
        ...
        return True