services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_codeindex
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  qdrant_storage:

networks:
  monitoring:
    external: true