version: '3.8'

services:
  # ==================== 个人版NebulaGraph单节点 ====================
  nebula-personal:
    image: vesoft/nebula-graph:v3.8.0
    container_name: nebula-personal
    hostname: nebula-personal
    ports:
      - "9669:9669"      # Graph服务端口
      - "19669:19669"    # HTTP监控端口
      - "19670:19670"    # HTTP2监控端口
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nebula-data:/data
      - ./nebula-logs:/logs
      - ./personal-nebula.conf:/usr/local/nebula/etc/nebula-graphd.conf
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "nebula-console", "-addr", "localhost", "-port", "9669", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS;"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ==================== 个人版监控配置 ====================
  nebula-stats-exporter-personal:
    image: vesoft/nebula-stats-exporter:v3.3.0
    container_name: nebula-stats-exporter-personal
    ports:
      - "9101:9100"  # 使用不同端口避免冲突
    volumes:
      - ./nebula-stats-exporter-personal.yaml:/config.yaml
    command:
      - "--bare-metal"
      - "--bare-metal-config=/config.yaml"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - nebula-personal

networks:
  monitoring:
    external: true

volumes:
  nebula-data:
  nebula-logs: