version: '3.8'

services:
  nebula-personal:
    image: vesoft/nebula-graph:v3.8.0
    container_name: nebula-personal
    ports:
      - "9669:9669"      # Graph服务端口
      - "19669:19669"    # HTTP端口
      - "19670:19670"    # HTTP2端口
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nebula-data:/data
      - ./nebula-logs:/logs
      - ./personal-nebula.conf:/usr/local/nebula/etc/nebula-graphd.conf
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "nebula-console", "-addr", "localhost", "-port", "9669", "-u", "root", "-p", "nebula", "-e", "SHOW HOSTS;"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  monitoring:
    external: true

volumes:
  nebula-data:
  nebula-logs: