rules:
  - id: swallowing-exceptions
    message: Exception swallowed without proper handling
    languages: [javascript, typescript, python, java, go, csharp]
    severity: WARNING
    patterns:
      - pattern: |
          try {
            ...
          } catch ($EX) {
            
          }
    metadata:
      category: reliability
      cwe: CWE-390
      confidence: HIGH

  - id: exception-without-finally
    message: Resource handling might miss cleanup in exception path
    languages: [javascript, typescript, python, java, go, csharp]
    severity: INFO
    patterns:
      - pattern: |
          try {
            $FILE = open(...)
            ...
          } catch (...) {
            ...
          }
    metadata:
      category: reliability
      cwe: CWE-459
      confidence: MEDIUM

  - id: return-in-finally
    message: Return statement in finally block may suppress exceptions
    languages: [javascript, typescript, python, java, go, csharp]
    severity: WARNING
    patterns:
      - pattern: |
          try {
            ...
          } finally {
            return ...;
          }
    metadata:
      category: correctness
      cwe: CWE-703
      confidence: HIGH

  - id: nested-try-catch
    message: Nested try-catch blocks may be simplified
    languages: [javascript, typescript, python, java, go, csharp]
    severity: INFO
    patterns:
      - pattern: |
          try {
            try {
              ...
            } catch ($EX1) {
              ...
            }
          } catch ($EX2) {
            ...
          }
    metadata:
      category: maintainability
      confidence: LOW