global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: 'codebase-index-mcp'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nebula-graph'
    static_configs:
      - targets: ['graphd:19670']
    metrics_path: '/stats'
    scrape_interval: 30s
    fallback_scrape_protocol: 'prometheus-text'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']