services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_codeindex
    ports:
      - "6333:6333"  # REST API  现在不需要使用。可以用127.0.0.1现成的qdrant
      - "6334:6334"  # gRPC API
    volumes:
      - ./storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  qdrant_storage:

networks:
  monitoring:
    external: true