version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: codebase-index-redis
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - codebase-index-network

volumes:
  redis_data:
    driver: local

networks:
  codebase-index-network:
    driver: bridge